/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as IllustrationRouteImport } from './routes/illustration'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioProjectIdRouteImport } from './routes/portfolio.$projectId'

const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const IllustrationRoute = IllustrationRouteImport.update({
  id: '/illustration',
  path: '/illustration',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioProjectIdRoute = PortfolioProjectIdRouteImport.update({
  id: '/portfolio/$projectId',
  path: '/portfolio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/illustration': typeof IllustrationRoute
  '/photography': typeof PhotographyRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/illustration': typeof IllustrationRoute
  '/photography': typeof PhotographyRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/illustration': typeof IllustrationRoute
  '/photography': typeof PhotographyRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/illustration'
    | '/photography'
    | '/portfolio/$projectId'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/illustration'
    | '/photography'
    | '/portfolio/$projectId'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/illustration'
    | '/photography'
    | '/portfolio/$projectId'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  IllustrationRoute: typeof IllustrationRoute
  PhotographyRoute: typeof PhotographyRoute
  PortfolioProjectIdRoute: typeof PortfolioProjectIdRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illustration': {
      id: '/illustration'
      path: '/illustration'
      fullPath: '/illustration'
      preLoaderRoute: typeof IllustrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$projectId': {
      id: '/portfolio/$projectId'
      path: '/portfolio/$projectId'
      fullPath: '/portfolio/$projectId'
      preLoaderRoute: typeof PortfolioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  IllustrationRoute: IllustrationRoute,
  PhotographyRoute: PhotographyRoute,
  PortfolioProjectIdRoute: PortfolioProjectIdRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
